<?php $pageTitle = 'Profil - Koperasi Syariah El Rahma Lombok Rinjani'; include 'includes/header.php'; ?>

<section class="bg-gradient-to-br from-brand-blue to-brand-navy py-16 text-white sm:py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><span class="text-sm font-bold uppercase tracking-widest text-white/65">Profil Koperasi</span><h1 class="mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-5xl">Wadah ekonomi anggota yang dikelola secara amanah.</h1><p class="mt-5 max-w-3xl text-lg leading-8 text-white/70">Mengenal identitas, arah, dan nilai yang menjadi dasar pelayanan <?= $site['name']; ?>.</p></div></section>

<section class="py-20"><div class="mx-auto grid max-w-7xl items-start gap-10 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><aside class="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm lg:sticky lg:top-28"><img class="h-32 w-32 rounded-2xl border border-slate-200 object-cover" src="assets/img/logo-elrahma.jpeg" alt="Logo <?= $site['name']; ?>"><h2 class="mt-5 text-xl font-black text-brand-navy"><?= $site['name']; ?></h2><p class="mt-2 text-slate-500"><?= $site['tagline']; ?></p></aside><div><span class="font-bold text-brand-red">Tentang Koperasi</span><h2 class="mt-3 text-3xl font-black text-brand-navy sm:text-4xl">Bertumbuh bersama masyarakat Lombok.</h2><div class="mt-6 space-y-4 leading-8 text-slate-600"><p><?= $site['name']; ?> bergerak dalam pengelolaan simpanan anggota, pembiayaan syariah, dan pemberdayaan usaha kecil. Koperasi hadir untuk memperkuat kebersamaan, mendukung kebutuhan permodalan, dan mendorong kegiatan ekonomi yang tertib serta bermanfaat.</p><p>Setiap layanan dijalankan dengan akad yang jelas, keputusan yang bertanggung jawab, dan semangat gotong royong sesuai prinsip koperasi serta syariah.</p></div><div class="mt-8 overflow-hidden rounded-2xl border border-slate-200"><?php $profileRows = [['Nama Lembaga', $site['name']], ['Bidang', 'Koperasi Simpan Pinjam dan Pembiayaan Syariah'], ['Fokus Program', 'Simpanan, pembiayaan, UMKM, dan edukasi anggota'], ['Wilayah Layanan', 'Lombok, Nusa Tenggara Barat']]; foreach ($profileRows as $row): ?><div class="grid gap-2 border-b border-slate-200 p-4 last:border-0 sm:grid-cols-[190px_1fr]"><strong class="text-brand-navy"><?= $row[0]; ?></strong><span class="text-slate-500"><?= $row[1]; ?></span></div><?php endforeach; ?></div></div></div></section>

<section class="bg-slate-50 py-20"><div class="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div class="rounded-3xl bg-brand-navy p-8 text-white"><span class="font-bold text-white/60">Visi</span><h2 class="mt-4 text-3xl font-black leading-tight">Menjadi koperasi syariah yang amanah, mandiri, dan bermanfaat bagi kesejahteraan anggota.</h2></div><div class="rounded-3xl border border-slate-200 bg-white p-8"><span class="font-bold text-brand-red">Misi</span><ul class="mt-5 space-y-4 text-slate-600"><li>✓ Meningkatkan budaya menabung dan pengelolaan keuangan anggota.</li><li>✓ Menyediakan pembiayaan syariah yang jelas, adil, dan mudah dipahami.</li><li>✓ Mendampingi UMKM anggota agar lebih tertib dan berkembang.</li><li>✓ Menjalankan koperasi secara transparan dan bertanggung jawab.</li></ul></div></div></section>

<section class="py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="mx-auto mb-10 max-w-2xl text-center"><span class="font-bold text-brand-red">Nilai Koperasi</span><h2 class="mt-3 text-3xl font-black text-brand-navy">Landasan dalam setiap pelayanan</h2></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><?php foreach ($values as $value): ?><div class="rounded-2xl border border-slate-200 p-6 font-semibold leading-7 text-slate-600 shadow-sm"><?= $value; ?></div><?php endforeach; ?></div></div></section>

<?php include 'includes/footer.php'; ?>
